### ISSUE TITLE
Segmentation fault encountered in worker

### ISSUE THREAD

**Issue by marketneutral** [neptune-ml/open-solution-ship-detection#6]
I've successfully prepared the masks and the meta data. However when I run the training (as `neptune run -x data --config configs/neptune.yaml main.py train --pipeline_name unet`) I get the following error:

```
2018-08-27 14-54-31 ships-detection >>> training
/anaconda3/envs/neptune/lib/python3.5/site-packages/click/core.py:535: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  return callback(*args, **kwargs)
2018-08-27 14:54:31 steppy >>> initializing Step xy_train...
2018-08-27 14:54:31 steppy >>> initializing experiment directories under /Users/jonathan/devwork/open-solution-ship-detection/experiments
2018-08-27 14:54:31 steppy >>> done: initializing experiment directories
2018-08-27 14:54:31 steppy >>> Step xy_train initialized
2018-08-27 14:54:31 steppy >>> initializing Step xy_inference...
2018-08-27 14:54:31 steppy >>> initializing experiment directories under /Users/jonathan/devwork/open-solution-ship-detection/experiments
2018-08-27 14:54:31 steppy >>> done: initializing experiment directories
2018-08-27 14:54:31 steppy >>> Step xy_inference initialized
2018-08-27 14:54:31 steppy >>> initializing Step loader...
2018-08-27 14:54:31 steppy >>> initializing experiment directories under /Users/jonathan/devwork/open-solution-ship-detection/experiments
2018-08-27 14:54:31 steppy >>> done: initializing experiment directories
2018-08-27 14:54:31 steppy >>> Step loader initialized
/anaconda3/envs/neptune/lib/python3.5/site-packages/toolkit/pytorch_transformers/architectures/unet.py:22: UserWarning: Please make sure, that your input tensor's dimensions are divisible by (pool_stride ** repeat_blocks)
  warnings.warn("Please make sure, that your input tensor's dimensions are divisible by "
2018-08-27 14:54:32 steppy >>> initializing Step unet...
2018-08-27 14:54:32 steppy >>> initializing experiment directories under /Users/jonathan/devwork/open-solution-ship-detection/experiments
2018-08-27 14:54:32 steppy >>> done: initializing experiment directories
2018-08-27 14:54:32 steppy >>> Step unet initialized
2018-08-27 14:54:32 steppy >>> cleaning cache...
2018-08-27 14:54:32 steppy >>> cleaning cache done
2018-08-27 14:54:32 steppy >>> Step xy_train, adapting inputs...
2018-08-27 14:54:32 steppy >>> Step xy_train, transforming...
2018-08-27 14:54:32 steppy >>> Step xy_inference, adapting inputs...
2018-08-27 14:54:32 steppy >>> Step xy_inference, transforming...
2018-08-27 14:54:32 steppy >>> Step loader, adapting inputs...
2018-08-27 14:54:32 steppy >>> Step loader, transforming...
2018-08-27 14:54:32 steppy >>> Step unet, adapting inputs...
2018-08-27 14:54:32 steppy >>> Step unet, fitting and transforming...
2018-08-27 14:54:32 steppy >>> initializing model weights...
2018-08-27 14-54-32 ships-detection >>> starting training...
2018-08-27 14-54-32 ships-detection >>> initial lr: 0.0001
2018-08-27 14-54-32 ships-detection >>> epoch 0 ...
ERROR: Unexpected segmentation fault encountered in worker.
Traceback (most recent call last):
  File "/anaconda3/envs/neptune/lib/python3.5/site-packages/deepsense/neptune/job_wrapper.py", line 107, in <module>
    execute()
  File "/anaconda3/envs/neptune/lib/python3.5/site-packages/deepsense/neptune/job_wrapper.py", line 103, in execute
    execfile(job_filepath, job_globals)
  File "/anaconda3/envs/neptune/lib/python3.5/site-packages/past/builtins/misc.py", line 82, in execfile
    exec_(code, myglobals, mylocals)
  File "main.py", line 89, in <module>
    main()
  File "/anaconda3/envs/neptune/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda3/envs/neptune/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/anaconda3/envs/neptune/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/anaconda3/envs/neptune/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda3/envs/neptune/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 27, in train
    pipeline_manager.train(pipeline_name, dev_mode)
  File "/Users/jonathan/devwork/open-solution-ship-detection/src/pipeline_manager.py", line 28, in train
    train(pipeline_name, dev_mode)
  File "/Users/jonathan/devwork/open-solution-ship-detection/src/pipeline_manager.py", line 77, in train
    pipeline.fit_transform(data)
  File "/anaconda3/envs/neptune/lib/python3.5/site-packages/steppy/base.py", line 323, in fit_transform
    step_output_data = self._cached_fit_transform(step_inputs)
  File "/anaconda3/envs/neptune/lib/python3.5/site-packages/steppy/base.py", line 443, in _cached_fit_transform
    step_output_data = self.transformer.fit_transform(**step_inputs)
  File "/anaconda3/envs/neptune/lib/python3.5/site-packages/steppy/base.py", line 605, in fit_transform
    self.fit(*args, **kwargs)
  File "/Users/jonathan/devwork/open-solution-ship-detection/src/models.py", line 68, in fit
    for batch_id, data in enumerate(batch_gen):
  File "/anaconda3/envs/neptune/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 275, in __next__
    idx, batch = self._get_batch()
  File "/anaconda3/envs/neptune/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 254, in _get_batch
    return self.data_queue.get()
  File "/anaconda3/envs/neptune/lib/python3.5/multiprocessing/queues.py", line 335, in get
    res = self._reader.recv_bytes()
  File "/anaconda3/envs/neptune/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/anaconda3/envs/neptune/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/anaconda3/envs/neptune/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/anaconda3/envs/neptune/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 175, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 33362) is killed by signal: Unknown signal: 0.
ERROR: Unexpected segmentation fault encountered in worker.
ERROR: Unexpected segmentation fault encountered in worker.
```

Do you have any ideas on this? Thank you very much.

**Comment by taraspiotr** [comment]
@marketneutral I've encountered similar error from PyTorch DataLoader before and it was caused by exceeding RAM, could it be the same case for you? I'm not sure, but maybe looking at htop while running pipeline would give some clues about that.
